VENDOR_ID=0x0000
PRODUCT_ID=0x0000
PRODUCT_NAME="Divergence Meter"
MANUFACTURER_NAME="Cvetko Alya"

WIFI_SSID="SSID"
WIFI_PASSWORD="PASSWD"
NTP_DAILY_SYNC_TIME="03:00"

TZ_OFFSET=0

DAYS_BETWEEN_DATES="[((2002,08,25), None, 2, 'L', 'Birthday'), ((2085,08,25), None, 2, 'R', 'Life expectancy')]"
